nelmio_api_doc:
  documentation: #<-- notice this change.
    enabled: true
    authentication:
      delivery: http
      type: bearer
    body_format:
      formats: [json, form] # array of enabled body formats,
      default_format: json

    api_base_path: /api
    swagger_version: "1.2"
    info:
      title: API-LAYERs
      description: "REST API"
      version: "0.1" # <-- notice this has been moved.